---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  flavor: 4GB

provisioner:
  require_chef_omnibus: true
  cookbook_files_glob: "**/*"

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[clamav-omnibus]
    attributes:
      omnibus:
        project_name: clamav
        project_version: 0.98.3
        project_build: 1
        build_user: omnibus
        build_dir: /home/omnibus/clamav
        install_dir: /opt/clamav
      package_cloud:
        user: <%= ENV['PACKAGE_CLOUD_USER'] %>
        token: <%= ENV['PACKAGE_CLOUD_TOKEN'] %>
