---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/omnibus/clamav', type: 'rsync']
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  flavor: 2GB

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[clamav-omnibus]
    attributes:
      omnibus:
        project_name: clamav
        project_version: 0.98.4
        project_build: 1
        build_user: omnibus
        build_dir: /home/omnibus/clamav
        install_dir: /opt/clamav
      packagecloud:
        user: <%= ENV['PACKAGECLOUD_USER'] %>
        token: <%= ENV['PACKAGECLOUD_TOKEN'] %>
