language: ruby

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
    - secure: Nla9OdwthQ2tvpr2HvkDSjlJ9l/AKiqmK/4woqlKjG3IBJJitSKsVH0zTkcBMuvTsTT54c/zwQAfSQSPfwfHVxTtF+j7eNFRxJvJ+u3rlMfvoyrJ1rJLjEk0SLfckEuFFstz77FXE5XitNxyzpahfB+3QwJdR9msFYTj1hSM0Ak=
    - secure: NI5CxWSQV8LvuOMSrFvi1MmvuDEwb4hvzd6WQtUFZ/0ueYmuze1dbnGglCdmL6yZX12A3WEwgDEYy8asfePO5dM3Mlt8k5hU2V+g1uIVBqYcy6Xf+dzkzb0PQeQV41vsPhQVgFU93+G91glCt4WPB5fx7/6WVQpAiBdux7MDzRk=
    - secure: fdRCmL/SafBeiQLrwT0bZSt/SaBcLE4C445vSX54pj7dzN7JAiv6dRuqHxibAwtEZsblVd0uT9nzBnKTQX+yoChP5umtEMomvoomxinaCkbaWZZ/lVE8675cKtPEsY0qA9lSmCuxbkm9DHirTLoWE1pSX4WjN6v7wZ/CuBFch20=
    - secure: aFtuLw5AHUr+DluhKsHowBflqaFDaoP+5vm/tmSCxaUw7/Ac7bT7f0amPvxPMzzzHM/Zf4yB7Pd2A3kPIzDC6SUrlIYxb0ow4Wv8Qb3AnidKhawFUWlbX2Ilm4bSWXmUpuJ0EHOBQ8hq8JN5x09Dr4ZBIa4AfvNmC3EDqJYpYlo=
