language: ruby

before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ''

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
    - PACKAGECLOUD_USER=RoboticCheese
    - DIGITALOCEAN_SSH_KEY_IDS=TBD
    - secure: "qUTq45+K5jFd6AMLP+clHWru6RrhiUICCyOeFVTggBqm7mAQ3dK9ZBHFp7nmVSRkx9WgrzjM3ce/CL2Nl73qnZ//7tZWVRlMnxR2r7Yz/39WGIhshWMFUweIgZT/FoJwVKeqbkwKsQexgLmSpjTk6YSQThI6SiOOWoTUYm1wz1g="
    - secure: "SDYTF8vvp7yXLFIz5idVYb6rYWJd5x1A369zfKjJLRQYgEqIjyeXpqUYxajXwUC7UYY0CfunSMoo4amG3IQh0JNIlIIL168AvEU+/RJTLmuVpDPcB12n42cFW/TDbyX5Pi4uo7UzBuQMP200vfdLNvNrXmG89zQJM9a93c4RfTk="
    - secure: "ovvUitM4RbcocBTtQfeP2HZ46j+jfs8zo+Ad7te0V0t3JM3wPmQjMvZ2XB0BcUVFmEEfsu6pjf6aMBCPZiAFkCL+v56X4F4XNOM0hHndviyQua7dETAsyTfYN3rO29mpo+ccxPPGSdOTedsdmfyYE3urjL0t93Hqkc8cxGydils="
    - secure: "qZG69xv8lyawl+SEgWmPc8LwjcsmkORkrjXA872my3vAF6vqBb/RGZ56WR4PWXqX8bgBooBjFbMu8hqgc4+xqqJFDFmY9FKz3P50EUKdfSagciYhgjtlYH5AlLvWVDmwBfliW+oU95bFRLzi9yqEz6ebxzlL1xTCJZtBO6IAXxc="
