language: ruby

rvm:
  - 2.1.1

before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ''
  # TODO: This is needed pending a fix to get Test Kitchen to respect
  # ENV['KITCHEN_LOCAL_YAML'] in the rake tasks in addition to in the CLI
  - cp .kitchen.travis.yml .kitchen.local.yml

env:
  global:
    # - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
    - PACKAGECLOUD_USER=RoboticCheese
    - DIGITALOCEAN_SSH_KEY_IDS=TBD
    - secure: "qUTq45+K5jFd6AMLP+clHWru6RrhiUICCyOeFVTggBqm7mAQ3dK9ZBHFp7nmVSRkx9WgrzjM3ce/CL2Nl73qnZ//7tZWVRlMnxR2r7Yz/39WGIhshWMFUweIgZT/FoJwVKeqbkwKsQexgLmSpjTk6YSQThI6SiOOWoTUYm1wz1g="
    - secure: "SDYTF8vvp7yXLFIz5idVYb6rYWJd5x1A369zfKjJLRQYgEqIjyeXpqUYxajXwUC7UYY0CfunSMoo4amG3IQh0JNIlIIL168AvEU+/RJTLmuVpDPcB12n42cFW/TDbyX5Pi4uo7UzBuQMP200vfdLNvNrXmG89zQJM9a93c4RfTk="
    - secure: "qZG69xv8lyawl+SEgWmPc8LwjcsmkORkrjXA872my3vAF6vqBb/RGZ56WR4PWXqX8bgBooBjFbMu8hqgc4+xqqJFDFmY9FKz3P50EUKdfSagciYhgjtlYH5AlLvWVDmwBfliW+oU95bFRLzi9yqEz6ebxzlL1xTCJZtBO6IAXxc="
